# Database (Supabase PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secretkey=${JWT_SECRETKEY}

tmdb.api.key = ${TMDB_API_KEY}
tmdb.base.url = https://api.themoviedb.org/3

# Port
server.port=${PORT:8080}